/** @format */

// Our sample parsedData format
// It is always sorted date ascending
export const sampleParsedData = [
  {
    date: "2023-05-27",
    liftType: "Back Squat",
    reps: 10,
    weight: 45,
    unitType: "lb",
    notes:
      'Use "Insert Rows" to always insert new data at the top of the spreadsheet',
    url: "",
  },
  {
    date: "2023-05-27",
    liftType: "Back Squat",
    reps: 5,
    weight: 95,
    unitType: "lb",
    notes: "Enter data anytime on mobile via the Google Sheets app.",
    url: "",
  },
  {
    date: "2023-05-27",
    liftType: "Back Squat",
    reps: 3,
    weight: 135,
    unitType: "lb",
    notes: "",
    url: "",
  },
  {
    date: "2023-05-27",
    liftType: "Back Squat",
    reps: 2,
    weight: 160,
    unitType: "lb",
    notes: "",
    url: "",
  },
  {
    date: "2023-05-27",
    liftType: "Back Squat",
    reps: 2,
    weight: 185,
    unitType: "lb",
    notes: "",
    url: "",
  },
  {
    date: "2023-05-27",
    liftType: "Back Squat",
    reps: 5,
    weight: 225,
    unitType: "lb",
    notes: "",
    url: "",
  },
  {
    date: "2023-05-27",
    liftType: "Back Squat",
    reps: 5,
    weight: 225,
    unitType: "lb",
    notes: "",
    url: "",
  },
  {
    date: "2023-05-27",
    liftType: "Back Squat",
    reps: 5,
    weight: 225,
    unitType: "lb",
    notes: "",
    url: "",
  },
  {
    date: "2023-05-27",
    liftType: "Overhead Press",
    reps: 5,
    weight: 45,
    unitType: "lb",
    notes: "",
    url: "",
  },
  {
    date: "2023-05-27",
    liftType: "Overhead Press",
    reps: 5,
    weight: 65,
    unitType: "lb",
    notes: "",
    url: "",
  },
  {
    date: "2023-05-27",
    liftType: "Overhead Press",
    reps: 5,
    weight: 65,
    unitType: "lb",
    notes: "",
    url: "",
  },
  {
    date: "2023-05-27",
    liftType: "Overhead Press",
    reps: 5,
    weight: 65,
    unitType: "lb",
    notes: "",
    url: "",
  },
  {
    date: "2023-05-25",
    liftType: "Back Squat",
    reps: 10,
    weight: 45,
    unitType: "lb",
    notes: "",
    url: "",
  },
  {
    date: "2023-05-25",
    liftType: "Back Squat",
    reps: 5,
    weight: 95,
    unitType: "lb",
    notes: "Some like to record all warm up sets, others just top sets.",
    url: "",
  },
  {
    date: "2023-05-25",
    liftType: "Back Squat",
    reps: 3,
    weight: 135,
    unitType: "lb",
    notes: "",
    url: "",
  },
  {
    date: "2023-05-25",
    liftType: "Back Squat",
    reps: 2,
    weight: 185,
    unitType: "lb",
    notes: "",
    url: "",
  },
  {
    date: "2023-05-25",
    liftType: "Back Squat",
    reps: 5,
    weight: 205,
    unitType: "lb",
    notes: "",
    url: "",
  },
  {
    date: "2023-05-25",
    liftType: "Back Squat",
    reps: 5,
    weight: 205,
    unitType: "lb",
    notes: "",
    url: "",
  },
  {
    date: "2023-05-25",
    liftType: "Back Squat",
    reps: 5,
    weight: 205,
    unitType: "lb",
    notes: "",
    url: "",
  },
  {
    date: "2023-05-25",
    liftType: "Back Squat",
    reps: 5,
    weight: 205,
    unitType: "lb",
    notes: "",
    url: "",
  },
  {
    date: "2023-05-25",
    liftType: "Bench Press",
    reps: 10,
    weight: 45,
    unitType: "lb",
    notes: "",
    url: "",
  },
  {
    date: "2023-05-25",
    liftType: "Bench Press",
    reps: 5,
    weight: 95,
    unitType: "lb",
    notes: "",
    url: "",
  },
  {
    date: "2023-05-25",
    liftType: "Bench Press",
    reps: 5,
    weight: 95,
    unitType: "lb",
    notes: "",
    url: "",
  },
  {
    date: "2023-05-25",
    liftType: "Bench Press",
    reps: 5,
    weight: 95,
    unitType: "lb",
    notes: "",
    url: "",
  },
  {
    date: "2023-05-25",
    liftType: "Deadlift",
    reps: 10,
    weight: 45,
    unitType: "lb",
    notes: "",
    url: "",
  },
  {
    date: "2023-05-25",
    liftType: "Deadlift",
    reps: 5,
    weight: 95,
    unitType: "lb",
    notes: "",
    url: "",
  },
  {
    date: "2023-05-25",
    liftType: "Deadlift",
    reps: 3,
    weight: 135,
    unitType: "lb",
    notes: "",
    url: "",
  },
  {
    date: "2023-05-25",
    liftType: "Deadlift",
    reps: 2,
    weight: 185,
    unitType: "lb",
    notes: "",
    url: "",
  },
  {
    date: "2023-05-25",
    liftType: "Deadlift",
    reps: 5,
    weight: 225,
    unitType: "lb",
    notes: "",
    url: "",
  },
  {
    date: "2023-05-23",
    liftType: "Back Squat",
    reps: 10,
    weight: 45,
    unitType: "lb",
    notes: "",
    url: "",
  },
  {
    date: "2023-05-23",
    liftType: "Back Squat",
    reps: 5,
    weight: 95,
    unitType: "lb",
    notes: "",
    url: "",
  },
  {
    date: "2023-05-23",
    liftType: "Back Squat",
    reps: 3,
    weight: 135,
    unitType: "lb",
    notes: "",
    url: "",
  },
  {
    date: "2023-05-23",
    liftType: "Back Squat",
    reps: 2,
    weight: 160,
    unitType: "lb",
    notes: "",
    url: "",
  },
  {
    date: "2023-05-23",
    liftType: "Back Squat",
    reps: 2,
    weight: 185,
    unitType: "lb",
    notes: "",
    url: "",
  },
  {
    date: "2023-05-23",
    liftType: "Back Squat",
    reps: 5,
    weight: 195,
    unitType: "lb",
    notes: "",
    url: "",
  },
  {
    date: "2023-05-23",
    liftType: "Back Squat",
    reps: 5,
    weight: 195,
    unitType: "lb",
    notes: "",
    url: "",
  },
  {
    date: "2023-05-23",
    liftType: "Back Squat",
    reps: 5,
    weight: 195,
    unitType: "lb",
    notes: "",
    url: "",
  },
  {
    date: "2023-05-23",
    liftType: "Overhead Press",
    reps: 5,
    weight: 45,
    unitType: "lb",
    notes: "",
    url: "",
  },
  {
    date: "2023-05-23",
    liftType: "Overhead Press",
    reps: 5,
    weight: 65,
    unitType: "lb",
    notes: "",
    url: "",
  },
  {
    date: "2023-05-23",
    liftType: "Overhead Press",
    reps: 5,
    weight: 65,
    unitType: "lb",
    notes: "",
    url: "",
  },
  {
    date: "2023-05-23",
    liftType: "Overhead Press",
    reps: 5,
    weight: 65,
    unitType: "lb",
    notes: "",
    url: "",
  },
  {
    date: "2023-05-20",
    liftType: "Back Squat",
    reps: 10,
    weight: 45,
    unitType: "lb",
    notes: "",
    url: "https://youtu.be/2kEC7X1FUIg?t=36",
  },
  {
    date: "2023-05-20",
    liftType: "Back Squat",
    reps: 5,
    weight: 95,
    unitType: "lb",
    notes: "",
    url: "",
  },
  {
    date: "2023-05-20",
    liftType: "Back Squat",
    reps: 3,
    weight: 135,
    unitType: "lb",
    notes: "",
    url: "",
  },
  {
    date: "2023-05-20",
    liftType: "Back Squat",
    reps: 2,
    weight: 160,
    unitType: "lb",
    notes: "",
    url: "",
  },
  {
    date: "2023-05-20",
    liftType: "Back Squat",
    reps: 5,
    weight: 185,
    unitType: "lb",
    notes: "",
    url: "",
  },
  {
    date: "2023-05-20",
    liftType: "Back Squat",
    reps: 5,
    weight: 185,
    unitType: "lb",
    notes: "",
    url: "",
  },
  {
    date: "2023-05-20",
    liftType: "Back Squat",
    reps: 5,
    weight: 185,
    unitType: "lb",
    notes: "",
    url: "",
  },
  {
    date: "2023-05-20",
    liftType: "Bench Press",
    reps: 10,
    weight: 45,
    unitType: "lb",
    notes: "",
    url: "",
  },
  {
    date: "2023-05-20",
    liftType: "Bench Press",
    reps: 5,
    weight: 80,
    unitType: "lb",
    notes: "",
    url: "",
  },
  {
    date: "2023-05-20",
    liftType: "Bench Press",
    reps: 5,
    weight: 80,
    unitType: "lb",
    notes: "",
    url: "",
  },
  {
    date: "2023-05-20",
    liftType: "Bench Press",
    reps: 5,
    weight: 80,
    unitType: "lb",
    notes: "",
    url: "",
  },
  {
    date: "2023-05-20",
    liftType: "Deadlift",
    reps: 10,
    weight: 45,
    unitType: "lb",
    notes: "",
    url: "",
  },
  {
    date: "2023-05-20",
    liftType: "Deadlift",
    reps: 5,
    weight: 95,
    unitType: "lb",
    notes: "",
    url: "",
  },
  {
    date: "2023-05-20",
    liftType: "Deadlift",
    reps: 3,
    weight: 135,
    unitType: "lb",
    notes: "",
    url: "",
  },
  {
    date: "2023-05-20",
    liftType: "Deadlift",
    reps: 2,
    weight: 185,
    unitType: "lb",
    notes: "",
    url: "",
  },
  {
    date: "2023-05-20",
    liftType: "Deadlift",
    reps: 5,
    weight: 215,
    unitType: "lb",
    notes: "",
    url: "",
  },
  {
    date: "2023-05-18",
    liftType: "Back Squat",
    reps: 10,
    weight: 45,
    unitType: "lb",
    notes: "",
    url: "",
  },
  {
    date: "2023-05-18",
    liftType: "Back Squat",
    reps: 5,
    weight: 95,
    unitType: "lb",
    notes: "",
    url: "",
  },
  {
    date: "2023-05-18",
    liftType: "Back Squat",
    reps: 3,
    weight: 135,
    unitType: "lb",
    notes: "",
    url: "",
  },
  {
    date: "2023-05-18",
    liftType: "Back Squat",
    reps: 2,
    weight: 160,
    unitType: "lb",
    notes: "",
    url: "",
  },
  {
    date: "2023-05-18",
    liftType: "Back Squat",
    reps: 5,
    weight: 180,
    unitType: "lb",
    notes: "",
    url: "",
  },
  {
    date: "2023-05-18",
    liftType: "Back Squat",
    reps: 5,
    weight: 180,
    unitType: "lb",
    notes: "",
    url: "",
  },
  {
    date: "2023-05-18",
    liftType: "Back Squat",
    reps: 5,
    weight: 180,
    unitType: "lb",
    notes: "",
    url: "",
  },
  {
    date: "2023-05-18",
    liftType: "Overhead Press",
    reps: 5,
    weight: 45,
    unitType: "lb",
    notes: "",
    url: "",
  },
  {
    date: "2023-05-18",
    liftType: "Overhead Press",
    reps: 5,
    weight: 60,
    unitType: "lb",
    notes: "",
    url: "",
  },
  {
    date: "2023-05-18",
    liftType: "Overhead Press",
    reps: 5,
    weight: 60,
    unitType: "lb",
    notes: "",
    url: "",
  },
  {
    date: "2023-05-18",
    liftType: "Overhead Press",
    reps: 5,
    weight: 60,
    unitType: "lb",
    notes: "",
    url: "",
  },
  {
    date: "2023-05-16",
    liftType: "Back Squat",
    reps: 10,
    weight: 45,
    unitType: "lb",
    notes: "",
    url: "",
  },
  {
    date: "2023-05-16",
    liftType: "Back Squat",
    reps: 5,
    weight: 95,
    unitType: "lb",
    notes: "",
    url: "",
  },
  {
    date: "2023-05-16",
    liftType: "Back Squat",
    reps: 3,
    weight: 135,
    unitType: "lb",
    notes: "",
    url: "",
  },
  {
    date: "2023-05-16",
    liftType: "Back Squat",
    reps: 2,
    weight: 160,
    unitType: "lb",
    notes: "",
    url: "",
  },
  {
    date: "2023-05-16",
    liftType: "Back Squat",
    reps: 5,
    weight: 175,
    unitType: "lb",
    notes: "",
    url: "",
  },
  {
    date: "2023-05-16",
    liftType: "Back Squat",
    reps: 5,
    weight: 175,
    unitType: "lb",
    notes: "",
    url: "",
  },
  {
    date: "2023-05-16",
    liftType: "Back Squat",
    reps: 5,
    weight: 175,
    unitType: "lb",
    notes: "",
    url: "",
  },
  {
    date: "2023-05-16",
    liftType: "Bench Press",
    reps: 10,
    weight: 45,
    unitType: "lb",
    notes: "",
    url: "",
  },
  {
    date: "2023-05-16",
    liftType: "Bench Press",
    reps: 5,
    weight: 75,
    unitType: "lb",
    notes: "",
    url: "",
  },
  {
    date: "2023-05-16",
    liftType: "Bench Press",
    reps: 5,
    weight: 75,
    unitType: "lb",
    notes: "",
    url: "",
  },
  {
    date: "2023-05-16",
    liftType: "Bench Press",
    reps: 5,
    weight: 75,
    unitType: "lb",
    notes: "",
    url: "",
  },
  {
    date: "2023-05-16",
    liftType: "Deadlift",
    reps: 10,
    weight: 45,
    unitType: "lb",
    notes: "",
    url: "",
  },
  {
    date: "2023-05-16",
    liftType: "Deadlift",
    reps: 5,
    weight: 95,
    unitType: "lb",
    notes: "",
    url: "",
  },
  {
    date: "2023-05-16",
    liftType: "Deadlift",
    reps: 3,
    weight: 135,
    unitType: "lb",
    notes: "",
    url: "",
  },
  {
    date: "2023-05-16",
    liftType: "Deadlift",
    reps: 5,
    weight: 200,
    unitType: "lb",
    notes: "",
    url: "",
  },
  {
    date: "2023-05-13",
    liftType: "Back Squat",
    reps: 10,
    weight: 45,
    unitType: "lb",
    notes: "",
    url: "",
  },
  {
    date: "2023-05-13",
    liftType: "Back Squat",
    reps: 3,
    weight: 95,
    unitType: "lb",
    notes: "",
    url: "",
  },
  {
    date: "2023-05-13",
    liftType: "Back Squat",
    reps: 2,
    weight: 135,
    unitType: "lb",
    notes: "",
    url: "",
  },
  {
    date: "2023-05-13",
    liftType: "Back Squat",
    reps: 5,
    weight: 170,
    unitType: "lb",
    notes: "",
    url: "",
  },
  {
    date: "2023-05-13",
    liftType: "Back Squat",
    reps: 5,
    weight: 170,
    unitType: "lb",
    notes: "",
    url: "",
  },
  {
    date: "2023-05-13",
    liftType: "Back Squat",
    reps: 5,
    weight: 170,
    unitType: "lb",
    notes: "",
    url: "",
  },
  {
    date: "2023-05-13",
    liftType: "Overhead Press",
    reps: 5,
    weight: 45,
    unitType: "lb",
    notes: "",
    url: "",
  },
  {
    date: "2023-05-13",
    liftType: "Overhead Press",
    reps: 5,
    weight: 60,
    unitType: "lb",
    notes: "",
    url: "",
  },
  {
    date: "2023-05-13",
    liftType: "Overhead Press",
    reps: 5,
    weight: 60,
    unitType: "lb",
    notes: "",
    url: "",
  },
  {
    date: "2023-05-13",
    liftType: "Overhead Press",
    reps: 5,
    weight: 60,
    unitType: "lb",
    notes: "",
    url: "",
  },
  {
    date: "2023-05-11",
    liftType: "Back Squat",
    reps: 10,
    weight: 45,
    unitType: "lb",
    notes: "",
    url: "",
  },
  {
    date: "2023-05-11",
    liftType: "Back Squat",
    reps: 3,
    weight: 95,
    unitType: "lb",
    notes: "",
    url: "",
  },
  {
    date: "2023-05-11",
    liftType: "Back Squat",
    reps: 2,
    weight: 135,
    unitType: "lb",
    notes: "",
    url: "",
  },
  {
    date: "2023-05-11",
    liftType: "Back Squat",
    reps: 5,
    weight: 165,
    unitType: "lb",
    notes: "",
    url: "",
  },
  {
    date: "2023-05-11",
    liftType: "Back Squat",
    reps: 5,
    weight: 165,
    unitType: "lb",
    notes: "",
    url: "",
  },
  {
    date: "2023-05-11",
    liftType: "Back Squat",
    reps: 5,
    weight: 165,
    unitType: "lb",
    notes: "",
    url: "",
  },
  {
    date: "2023-05-11",
    liftType: "Bench Press",
    reps: 10,
    weight: 45,
    unitType: "lb",
    notes: "",
    url: "",
  },
  {
    date: "2023-05-11",
    liftType: "Bench Press",
    reps: 5,
    weight: 65,
    unitType: "lb",
    notes: "",
    url: "",
  },
  {
    date: "2023-05-11",
    liftType: "Bench Press",
    reps: 5,
    weight: 65,
    unitType: "lb",
    notes: "",
    url: "",
  },
  {
    date: "2023-05-11",
    liftType: "Bench Press",
    reps: 5,
    weight: 65,
    unitType: "lb",
    notes: "",
    url: "",
  },
  {
    date: "2023-05-11",
    liftType: "Deadlift",
    reps: 10,
    weight: 45,
    unitType: "lb",
    notes: "",
    url: "",
  },
  {
    date: "2023-05-11",
    liftType: "Deadlift",
    reps: 5,
    weight: 95,
    unitType: "lb",
    notes: "",
    url: "",
  },
  {
    date: "2023-05-11",
    liftType: "Deadlift",
    reps: 5,
    weight: 135,
    unitType: "lb",
    notes: "",
    url: "",
  },
  {
    date: "2023-05-11",
    liftType: "Deadlift",
    reps: 5,
    weight: 190,
    unitType: "lb",
    notes: "",
    url: "",
  },
  {
    date: "2023-05-09",
    liftType: "Back Squat",
    reps: 10,
    weight: 45,
    unitType: "lb",
    notes: "",
    url: "",
  },
  {
    date: "2023-05-09",
    liftType: "Back Squat",
    reps: 5,
    weight: 95,
    unitType: "lb",
    notes: "",
    url: "",
  },
  {
    date: "2023-05-09",
    liftType: "Back Squat",
    reps: 3,
    weight: 135,
    unitType: "lb",
    notes: "",
    url: "",
  },
  {
    date: "2023-05-09",
    liftType: "Back Squat",
    reps: 5,
    weight: 160,
    unitType: "lb",
    notes: "",
    url: "",
  },
  {
    date: "2023-05-09",
    liftType: "Back Squat",
    reps: 5,
    weight: 160,
    unitType: "lb",
    notes: "",
    url: "",
  },
  {
    date: "2023-05-09",
    liftType: "Back Squat",
    reps: 5,
    weight: 160,
    unitType: "lb",
    notes: "",
    url: "",
  },
  {
    date: "2023-05-09",
    liftType: "Overhead Press",
    reps: 5,
    weight: 45,
    unitType: "lb",
    notes: "",
    url: "",
  },
  {
    date: "2023-05-09",
    liftType: "Overhead Press",
    reps: 5,
    weight: 55,
    unitType: "lb",
    notes: "",
    url: "",
  },
  {
    date: "2023-05-09",
    liftType: "Overhead Press",
    reps: 5,
    weight: 55,
    unitType: "lb",
    notes: "",
    url: "",
  },
  {
    date: "2023-05-09",
    liftType: "Overhead Press",
    reps: 5,
    weight: 55,
    unitType: "lb",
    notes: "",
    url: "",
  },
  {
    date: "2023-05-06",
    liftType: "Back Squat",
    reps: 10,
    weight: 45,
    unitType: "lb",
    notes: "",
    url: "",
  },
  {
    date: "2023-05-06",
    liftType: "Back Squat",
    reps: 5,
    weight: 95,
    unitType: "lb",
    notes: "",
    url: "",
  },
  {
    date: "2023-05-06",
    liftType: "Back Squat",
    reps: 5,
    weight: 155,
    unitType: "lb",
    notes: "",
    url: "",
  },
  {
    date: "2023-05-06",
    liftType: "Back Squat",
    reps: 5,
    weight: 155,
    unitType: "lb",
    notes: "",
    url: "",
  },
  {
    date: "2023-05-06",
    liftType: "Back Squat",
    reps: 5,
    weight: 155,
    unitType: "lb",
    notes: "Now wearing lever belt.",
    url: "",
  },
  {
    date: "2023-05-06",
    liftType: "Bench Press",
    reps: 10,
    weight: 45,
    unitType: "lb",
    notes: "",
    url: "",
  },
  {
    date: "2023-05-06",
    liftType: "Bench Press",
    reps: 5,
    weight: 55,
    unitType: "lb",
    notes: "",
    url: "",
  },
  {
    date: "2023-05-06",
    liftType: "Bench Press",
    reps: 5,
    weight: 55,
    unitType: "lb",
    notes: "",
    url: "",
  },
  {
    date: "2023-05-06",
    liftType: "Bench Press",
    reps: 5,
    weight: 55,
    unitType: "lb",
    notes: "",
    url: "",
  },
  {
    date: "2023-05-06",
    liftType: "Deadlift",
    reps: 10,
    weight: 45,
    unitType: "lb",
    notes: "",
    url: "",
  },
  {
    date: "2023-05-06",
    liftType: "Deadlift",
    reps: 5,
    weight: 95,
    unitType: "lb",
    notes: "",
    url: "",
  },
  {
    date: "2023-05-06",
    liftType: "Deadlift",
    reps: 5,
    weight: 170,
    unitType: "lb",
    notes: "",
    url: "",
  },
  {
    date: "2023-05-04",
    liftType: "Back Squat",
    reps: 10,
    weight: 45,
    unitType: "lb",
    notes: "",
    url: "",
  },
  {
    date: "2023-05-04",
    liftType: "Back Squat",
    reps: 5,
    weight: 95,
    unitType: "lb",
    notes: "",
    url: "",
  },
  {
    date: "2023-05-04",
    liftType: "Back Squat",
    reps: 5,
    weight: 145,
    unitType: "lb",
    notes: "",
    url: "",
  },
  {
    date: "2023-05-04",
    liftType: "Back Squat",
    reps: 5,
    weight: 145,
    unitType: "lb",
    notes: "",
    url: "",
  },
  {
    date: "2023-05-04",
    liftType: "Back Squat",
    reps: 5,
    weight: 145,
    unitType: "lb",
    notes: "Back squats making feel strong.",
    url: "",
  },
  {
    date: "2023-05-04",
    liftType: "Overhead Press",
    reps: 5,
    weight: 45,
    unitType: "lb",
    notes: "",
    url: "",
  },
  {
    date: "2023-05-04",
    liftType: "Overhead Press",
    reps: 5,
    weight: 45,
    unitType: "lb",
    notes: "",
    url: "",
  },
  {
    date: "2023-05-04",
    liftType: "Overhead Press",
    reps: 5,
    weight: 45,
    unitType: "lb",
    notes: "",
    url: "",
  },
  {
    date: "2023-05-02",
    liftType: "Back Squat",
    reps: 10,
    weight: 45,
    unitType: "lb",
    notes: "",
    url: "",
  },
  {
    date: "2023-05-02",
    liftType: "Back Squat",
    reps: 5,
    weight: 95,
    unitType: "lb",
    notes: "",
    url: "",
  },
  {
    date: "2023-05-02",
    liftType: "Back Squat",
    reps: 5,
    weight: 135,
    unitType: "lb",
    notes: "",
    url: "",
  },
  {
    date: "2023-05-02",
    liftType: "Back Squat",
    reps: 5,
    weight: 135,
    unitType: "lb",
    notes: "",
    url: "",
  },
  {
    date: "2023-05-02",
    liftType: "Back Squat",
    reps: 5,
    weight: 135,
    unitType: "lb",
    notes: "First session complete!",
    url: "",
  },
  {
    date: "2023-05-02",
    liftType: "Bench Press",
    reps: 5,
    weight: 45,
    unitType: "lb",
    notes: "",
    url: "",
  },
  {
    date: "2023-05-02",
    liftType: "Bench Press",
    reps: 5,
    weight: 45,
    unitType: "lb",
    notes: "",
    url: "",
  },
  {
    date: "2023-05-02",
    liftType: "Bench Press",
    reps: 5,
    weight: 45,
    unitType: "lb",
    notes: "",
    url: "",
  },
  {
    date: "2023-05-02",
    liftType: "Deadlift",
    reps: 10,
    weight: 45,
    unitType: "lb",
    notes: "",
    url: "",
  },
  {
    date: "2023-05-02",
    liftType: "Deadlift",
    reps: 5,
    weight: 95,
    unitType: "lb",
    notes: "",
    url: "",
  },
  {
    date: "2023-05-02",
    liftType: "Deadlift",
    reps: 5,
    weight: 145,
    unitType: "lb",
    notes: "",
    url: "",
  },
];
